import { type ScrollBoxRenderable } from "@opentui/core";
import type { Dispatch, MutableRefObject, SetStateAction } from "react";
import { type Controller } from "../../../application/client-runtime.ts";
import type { DevctlConfig } from "../../../domain/config/types.ts";
import type { LogEvent } from "../../../domain/logs/logs.ts";
import type { PortHolder } from "../../../domain/net/ports.ts";
import { type StatusSnapshot } from "../../../domain/status.ts";
import { type CommandSpec } from "../commands.ts";
import { type TuiConfig } from "../tui-config.ts";
import { type ConfirmDetail, type ConfirmKind, type Overlay, type Screen, type SlashPicker } from "../types.ts";
import type { useDiagnostics } from "./use-diagnostics.ts";
import type { useLifecycle } from "./use-lifecycle.ts";
import type { useLogView } from "./use-log-view.ts";
import type { useMcpControls } from "./use-mcp-controls.ts";
import type { usePreferences } from "./use-preferences.ts";

export type KeyboardUi = {
  screen: Screen;
  overlay: Overlay;
  onQuit: (detach?: boolean) => void;
  onDown: (keepServices: boolean) => void;
  closeOverlay: () => void;
  confirmKind: ConfirmKind;
  confirmDetail: ConfirmDetail | undefined;
  portTarget: PortHolder | undefined;
  profile: string;
  listCursor: number;
  names: string[];
  listCount: number;
  openDetail: (name: string) => void;
  copySelection: () => Promise<void>;
  height: number;
  paletteIndex: number;
  applyTheme: (name: string) => void;
  runCommand: (spec: CommandSpec, args: string[]) => void | Promise<void>;
  saveConfigBuffer: () => void;
  filtered: CommandSpec[];
  slashIndex: number;
  submitSlash: () => void;
  advanceWizard?: () => void;
  bootErrorMissing: boolean;
  bootError?: string;
  createStarterConfig: (repo: string) => string;
  startWizard: () => void;
  toggleChecked: (name: string) => void;
  checked: string[];
  detailName: string;
  refresh: () => Promise<StatusSnapshot | undefined>;
  openConfigBuffer: () => void;
  setOverlay: Dispatch<SetStateAction<Overlay>>;
  setConfirmKind: Dispatch<SetStateAction<ConfirmKind>>;
  setConfirmDetail: Dispatch<SetStateAction<ConfirmDetail>>;
  setPortTarget: Dispatch<SetStateAction<PortHolder | undefined>>;
  setLogDetail: Dispatch<SetStateAction<LogEvent | undefined>>;
  logDetail?: LogEvent;
  setLogSearch: ReturnType<typeof useLogView>["setLogSearch"];
  setProfile: Dispatch<SetStateAction<string>>;
  setStatus: Dispatch<SetStateAction<string>>;
  setPaletteIndex: Dispatch<SetStateAction<number>>;
  setSlashIndex: Dispatch<SetStateAction<number>>;
  setQuery: Dispatch<SetStateAction<string>>;
  setSlashPicker: Dispatch<SetStateAction<SlashPicker>>;
  setScreen: Dispatch<SetStateAction<Screen>>;
  setSelected: Dispatch<SetStateAction<number>>;
  setChecked: Dispatch<SetStateAction<string[]>>;
  setConfigEditError: Dispatch<SetStateAction<string>>;
  freePort: (holder: PortHolder) => Promise<void>;
};

export type KeyboardRefs = {
  interruptArmedAt: MutableRefObject<number>;
  leaderTimer: MutableRefObject<ReturnType<typeof setTimeout> | undefined>;
  logDetailsScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
  scrollTextScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
  routeDetailsScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
  planScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
  helpScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
  configScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
  detailScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
};

export type OverlayKeyCtx = KeyboardUi & {
  tui: TuiConfig;
  confirmAction: (mode?: "cascade") => void;
  planBusy: boolean;
  leaderTimer: MutableRefObject<ReturnType<typeof setTimeout> | undefined>;
  logDetailsScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
  scrollTextScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
  routeDetailsScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
  planScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
  helpScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
  revertThemePreview: () => void;
  setThemeName: (name: string) => void;
};

export type ScreenKeyCtx = KeyboardUi & {
  tui: TuiConfig;
  controller: Controller | undefined;
  cfg: DevctlConfig | undefined;
  snap: StatusSnapshot | undefined;
  logSearchFocused: boolean;
  logsFullscreen: boolean;
  logSources: string[];
  logService: string;
  logs: ReturnType<typeof useLogView>["logs"];
  logShowTimestamps: boolean;
  logShowMeta: boolean;
  logWrap: ReturnType<typeof useLogView>["logWrap"];
  showSystemLogs: boolean;
  logPinned: boolean;
  dashboardLogCursor: number;
  applyLogCursor: ReturnType<typeof useLogView>["applyLogCursor"];
  applyDashboardLogCursor: ReturnType<typeof useLogView>["applyDashboardLogCursor"];
  jumpToLatestLogs: ReturnType<typeof useLogView>["jumpToLatestLogs"];
  toggleSystemLogs: ReturnType<typeof useLogView>["toggleSystemLogs"];
  clearLogs: ReturnType<typeof useLogView>["clearLogs"];
  setLogSearchFocused: ReturnType<typeof useLogView>["setLogSearchFocused"];
  setLogsFullscreen: ReturnType<typeof useLogView>["setLogsFullscreen"];
  setLogService: ReturnType<typeof useLogView>["setLogService"];
  setLogShowTimestamps: ReturnType<typeof useLogView>["setLogShowTimestamps"];
  setLogShowMeta: ReturnType<typeof useLogView>["setLogShowMeta"];
  setPaused: ReturnType<typeof useLogView>["setPaused"];
  setErrorOnly: ReturnType<typeof useLogView>["setErrorOnly"];
  setLogWrap: ReturnType<typeof useLogView>["setLogWrap"];
  beginStart: ReturnType<typeof useLifecycle>["beginStart"];
  beginStop: ReturnType<typeof useLifecycle>["beginStop"];
  beginRestart: ReturnType<typeof useLifecycle>["beginRestart"];
  applyMcpPortDraft: ReturnType<typeof useMcpControls>["applyMcpPortDraft"];
  toggleMcp: ReturnType<typeof useMcpControls>["toggleMcp"];
  toggleMcpTool: ReturnType<typeof useMcpControls>["toggleMcpTool"];
  copyFocusedMcpSnippet: ReturnType<typeof useMcpControls>["copyFocusedMcpSnippet"];
  persistMcpPort: ReturnType<typeof useMcpControls>["persistMcpPort"];
  restartMcpOnPort: ReturnType<typeof useMcpControls>["restartMcpOnPort"];
  setMcpPortDraft: ReturnType<typeof useMcpControls>["setMcpPortDraft"];
  settingRows: ReturnType<typeof usePreferences>["settingRows"];
  persistPrefs: ReturnType<typeof usePreferences>["persistPrefs"];
  cycleSetting: ReturnType<typeof usePreferences>["cycleSetting"];
  toggleMouse: ReturnType<typeof usePreferences>["toggleMouse"];
  setDoctorTick: ReturnType<typeof useDiagnostics>["setDoctorTick"];
  refreshAuth: ReturnType<typeof useDiagnostics>["refreshAuth"];
  configScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
  detailScrollRef: MutableRefObject<ScrollBoxRenderable | null>;
  handleEnter: () => void;
};
