// Regenerates the embedded SPA blob that a `bun build --compile` binary cannot
// read from disk: presentation/web/assets.generated.ts. Copies drift;
// assets.test.ts fails until this script is re-run.
//
//   bun run build:web
import { createHash } from "node:crypto";
import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative } from "node:path";

const appRoot = dirname(import.meta.dir);
const webRoot = join(appRoot, "web");
const outModule = join(appRoot, "src", "presentation", "web", "assets.generated.ts");

export function listWebSources(root = webRoot): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const name of readdirSync(dir).sort()) {
      const full = join(dir, name);
      if (statSync(full).isDirectory()) {
        walk(full);
      } else {
        out.push(full);
      }
    }
  };
  walk(root);
  return out.sort();
}

// Hash LF-normalized UTF-8, not raw bytes. Windows checkouts with
// core.autocrlf=true would otherwise disagree with the Linux-built
// WEB_SOURCES_HASH even when the files are the same. Paths use `/` so a
// nested source on Windows cannot drift the hash either.
function normalizeEol(text: string): string {
  return text.replace(/\r\n/g, "\n");
}

export function hashWebSources(root = webRoot): string {
  const hash = createHash("sha256");
  for (const file of listWebSources(root)) {
    hash.update(relative(root, file).replaceAll("\\", "/"));
    hash.update("\0");
    hash.update(normalizeEol(readFileSync(file, "utf8")));
    hash.update("\0");
  }
  return hash.digest("hex");
}

function inlineAssets(html: string, dir: string): string {
  // Stylesheets first: inlined JS contains fake <link href="%s"> strings that
  // must not be treated as real tags.
  let out = html.replace(/<link\b([^>]*)\/?>/gi, (all, attrs: string) => {
    if (!/\brel="stylesheet"/i.test(attrs)) {
      return all;
    }
    const href = /\bhref="([^"]+)"/.exec(attrs);
    if (!href?.[1]) {
      return all;
    }
    const body = readFileSync(join(dir, href[1]), "utf8").replace(/<\/style/gi, "<\\/style");
    return `<style>${body}</style>`;
  });
  out = out.replace(/<script\b([^>]*)><\/script>/gi, (all, attrs: string) => {
    const src = /\bsrc="([^"]+)"/.exec(attrs);
    if (!src?.[1]) {
      return all;
    }
    // An inlined bundle that contains `"</script>"` (React's createElement
    // probe) would otherwise close this tag early and dump the rest as text.
    const body = readFileSync(join(dir, src[1]), "utf8").replace(/<\/script/gi, "<\\/script");
    const rest = attrs.replace(/\bsrc="[^"]+"/i, "").replace(/\s+/g, " ").trim();
    return `<script${rest ? ` ${rest}` : ""}>${body}</script>`;
  });
  // Drop network URLs from the blob, but keep SVG/MathML namespace URIs —
  // stripping those makes React create generic Elements with no .style.
  return out.replace(/https?:\/\/(?!www\.w3\.org\/)[^\s"'`<>\\]+/g, "");
}

export function renderWebAssetsModule(html: string, sourcesHash: string): string {
  return `// GENERATED by scripts/build-web-assets.ts — do not edit by hand.
// Source of truth: app/web/. Run \`bun run build:web\` after editing those
// files; assets.test.ts fails until this matches them.

export const WEB_INDEX_HTML = ${JSON.stringify(html)};
export const WEB_SOURCES_HASH = ${JSON.stringify(sourcesHash)};
`;
}

if (import.meta.main) {
  const outdir = mkdtempSync(join(tmpdir(), "devctl-web-"));
  mkdirSync(outdir, { recursive: true });
  try {
    const result = await Bun.build({
      entrypoints: [join(webRoot, "index.html")],
      target: "browser",
      minify: true,
      outdir,
      sourcemap: "none",
      define: {
        "process.env.NODE_ENV": JSON.stringify("production"),
      },
    });
    if (!result.success) {
      const logs = result.logs.map((log) => String(log)).join("\n");
      throw new Error(`Bun.build failed\n${logs}`);
    }
    const htmlFile = result.outputs.find((out) => out.path.endsWith(".html"))?.path
      ?? join(outdir, "index.html");
    const html = inlineAssets(readFileSync(htmlFile, "utf8"), dirname(htmlFile));
    const sourcesHash = hashWebSources(webRoot);
    writeFileSync(outModule, renderWebAssetsModule(html, sourcesHash));
    process.stdout.write(`wrote ${outModule}\n`);
  } finally {
    rmSync(outdir, { recursive: true, force: true });
  }
}
