// Regenerates the MCP embeds that a `bun build --compile` binary cannot read
// from disk: guide.generated.ts (onboarding skill) and docs.generated.ts
// (docs/*.md). Copies drift; guide.test.ts and docs-search.test.ts fail until
// this script is re-run.
//
//   bun run sync-guide
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const appRoot = dirname(import.meta.dir);
const repoRoot = dirname(appRoot);
const skill = join(repoRoot, "skills", "devctl-onboard");

export const GUIDE_SOURCES = [
  { key: "procedure", file: join(skill, "SKILL.md") },
  { key: "authoring", file: join(skill, "references", "authoring.md") },
  { key: "discovery", file: join(skill, "references", "discovery.md") },
] as const;

// A backtick or ${ in the source would terminate or interpolate the template
// literal this writes, so both are escaped; the test reads the runtime value,
// which unescapes back to the original bytes.
function escapeTemplate(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

// CRLF has to go before the text reaches the template literal. JavaScript
// normalizes line terminators *inside* template literals, so a CRLF checkout
// (Windows, core.autocrlf=true) would embed LF while the file on disk still
// has CRLF — the two would never compare equal no matter how the test reads
// them. Normalizing here also keeps this generated file byte-identical
// whichever platform runs the script, so a Windows contributor cannot produce
// a spurious diff.
function normalizeEol(text: string): string {
  return text.replace(/\r\n/g, "\n");
}

export function renderGuideModule(): string {
  const entries = GUIDE_SOURCES.map(({ key, file }) => {
    const body = normalizeEol(readFileSync(file, "utf8"));
    return `  ${key}: \`${escapeTemplate(body)}\`,`;
  }).join("\n");
  return `// GENERATED by scripts/sync-guide.ts — do not edit by hand.
// Source of truth: skills/devctl-onboard/. Run \`bun run sync-guide\` after
// editing those files; guide.test.ts fails until this matches them.

export const GUIDE_SECTIONS = {
${entries}
} as const;

export type GuideSection = keyof typeof GUIDE_SECTIONS;
`;
}

const DOC_SKIP = ["devctl-architecture.md"] as const;

function listDocFiles(): string[] {
  const skip = new Set<string>(DOC_SKIP);
  return readdirSync(join(repoRoot, "docs"))
    .filter((name) => name.endsWith(".md") && !skip.has(name))
    .sort();
}

function pageTitle(name: string, body: string): string {
  const heading = /^#\s+(.+)$/m.exec(body);
  return heading?.[1]?.trim() || name.replace(/\.md$/, "");
}

function renderDocsModule(): string {
  const entries = listDocFiles()
    .map((name) => {
      const body = normalizeEol(readFileSync(join(repoRoot, "docs", name), "utf8"));
      const title = pageTitle(name, body);
      const path = `docs/${name}`;
      return `  { path: ${JSON.stringify(path)}, title: ${JSON.stringify(title)}, body: \`${escapeTemplate(body)}\` },`;
    })
    .join("\n");
  return `// GENERATED by scripts/sync-guide.ts — do not edit by hand.
// Source of truth: docs/*.md (except the historical architecture spec).
// Run \`bun run sync-guide\` after editing those files; docs-search.test.ts
// fails until this matches them.

export type EmbeddedDocPage = {
  readonly path: string;
  readonly title: string;
  readonly body: string;
};

export const DOC_PAGES: readonly EmbeddedDocPage[] = [
${entries}
];
`;
}

if (import.meta.main) {
  const mcp = join(appRoot, "src", "presentation", "mcp");
  const guideOut = join(mcp, "guide.generated.ts");
  const docsOut = join(mcp, "docs.generated.ts");
  writeFileSync(guideOut, renderGuideModule());
  writeFileSync(docsOut, renderDocsModule());
  process.stdout.write(`wrote ${guideOut}\n`);
  process.stdout.write(`wrote ${docsOut}\n`);
}
