// Regenerates src/presentation/mcp/guide.generated.ts from the skill files at the repo root.
//
// The MCP `get_setup_guide` tool has to serve this text from inside a
// `bun build --compile` binary, which is a single file with no repo alongside
// it — so the text cannot be read from skills/ at runtime and must be compiled
// in. That makes two copies, and two copies drift; guide.test.ts asserts this
// file is in sync and tells you to run this script when it is not.
//
//   bun run sync-guide
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const appRoot = dirname(import.meta.dir);
const repoRoot = dirname(appRoot);
const skill = join(repoRoot, "skills", "devctl-onboard");

export const GUIDE_SOURCES = [
  { key: "procedure", file: join(skill, "SKILL.md") },
  { key: "authoring", file: join(skill, "references", "authoring.md") },
  { key: "discovery", file: join(skill, "references", "discovery.md") },
] as const;

// A backtick or ${ in the source would terminate or interpolate the template
// literal this writes, so both are escaped; the test reads the runtime value,
// which unescapes back to the original bytes.
function escapeTemplate(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

// CRLF has to go before the text reaches the template literal. JavaScript
// normalizes line terminators *inside* template literals, so a CRLF checkout
// (Windows, core.autocrlf=true) would embed LF while the file on disk still
// has CRLF — the two would never compare equal no matter how the test reads
// them. Normalizing here also keeps this generated file byte-identical
// whichever platform runs the script, so a Windows contributor cannot produce
// a spurious diff.
function normalizeEol(text: string): string {
  return text.replace(/\r\n/g, "\n");
}

export function renderGuideModule(): string {
  const entries = GUIDE_SOURCES.map(({ key, file }) => {
    const body = normalizeEol(readFileSync(file, "utf8"));
    return `  ${key}: \`${escapeTemplate(body)}\`,`;
  }).join("\n");
  return `// GENERATED by scripts/sync-guide.ts — do not edit by hand.
// Source of truth: skills/devctl-onboard/. Run \`bun run sync-guide\` after
// editing those files; guide.test.ts fails until this matches them.

export const GUIDE_SECTIONS = {
${entries}
} as const;

export type GuideSection = keyof typeof GUIDE_SECTIONS;
`;
}

if (import.meta.main) {
  const out = join(appRoot, "src", "presentation", "mcp", "guide.generated.ts");
  writeFileSync(out, renderGuideModule());
  process.stdout.write(`wrote ${out}\n`);
}
