// GENERATED by scripts/sync-guide.ts — do not edit by hand.
// Source of truth: skills/devctl-onboard/. Run `bun run sync-guide` after
// editing those files; guide.test.ts fails until this matches them.

export const GUIDE_SECTIONS = {
  procedure: `---
name: devctl-onboard
description: Survey a repository — its runnable services, docker-compose, Terraform, Kubernetes manifests, .env files, task runners — and author a validated .devctl configuration for it. Use when asked to onboard a repo to devctl, add or fix .devctl/config.yaml, generate devctl services/profiles/proxy routes, or diagnose why a devctl config fails to load.
---

# Onboarding a repository to devctl

You are producing a \`.devctl/\` configuration that runs this repository's services
locally, under one supervisor, with the right ports, dependency order, health
checks, environment, and (where the repo talks to Google Cloud) identity and
proxy routes.

Work in four phases: **inventory → draft → validate → verify running**. Do not
skip validation; \`devctl\` rejects unknown fields and unresolvable references at
load time, so an unvalidated config is usually a broken one.

## Ground rules

- **Read before you write.** Never author a service you have not found a real
  start command for in the repo.
- **Never copy a secret value into YAML.** Reference secrets by name. See
  [Secrets](#secrets-name-only-always) below.
- **Never invent cloud identifiers.** Service-account emails, IAP audiences and
  project IDs come from Terraform, existing config, or the user — not from you.
- **Unknown fields are rejected.** Every key you write must appear in
  \`references/authoring.md\`. When unsure, check it rather than guessing.
- The user's existing \`.devctl/\` is theirs. If one exists, treat this as an
  edit, diff your changes, and say what you are changing before you write.

## Phase 1 — Inventory (read-only)

Build a picture of what this repo actually runs. Read
\`references/discovery.md\` for the full signal → service mapping; the short
version:

\`\`\`bash
# Runnable units
ls docker-compose*.y*ml Procfile Makefile Taskfile.y*ml 2>/dev/null
find . -maxdepth 3 \\( -name package.json -o -name pyproject.toml -o -name go.mod \\
  -o -name Cargo.toml -o -name pom.xml -o -name build.gradle\\* \\) \\
  -not -path '*/node_modules/*' -not -path '*/.venv/*'

# Environment surface (names only — do not print values)
find . -maxdepth 3 -name '.env*' -not -path '*/node_modules/*'

# Cloud shape
find . -maxdepth 4 -name '*.tf' -o -name '*.tfvars' | head
find . -maxdepth 4 -path '*k8s*' -name '*.y*ml' -o -name 'skaffold.y*ml'
\`\`\`

Produce a short table before writing anything — service name, working dir,
start command, port, depends-on, health endpoint, env keys required. Show it to
the user when the repo has more than about three services; that table is the
thing worth correcting, and correcting it is far cheaper than correcting YAML.

Port collisions are the most common inventory error. Ports must be unique
across every service in the config. When the repo does not pin ports, either
assign a contiguous private band (e.g. \`18000\`, \`18001\`, …) or use \`auto\` and
let devctl allocate.

### Terraform: infer, do not transcribe

Terraform describes **deployed** infrastructure. devctl runs **local
processes**. A \`google_cloud_run_service\` is not a devctl service.

A Terraform resource becomes a devctl service **only when the repo also
contains runnable source for it.** Otherwise it is either a proxy upstream or
nothing at all. What Terraform legitimately contributes:

| Terraform | Becomes |
|---|---|
| \`google_service_account\` | \`identity.service_account\`, or a route's \`auth.identity.service_account\` |
| IAP brand / OAuth client / \`iap_web_*\` | route \`auth.type: iap\` + \`audience\` |
| \`google_secret_manager_secret\` | a name under \`environment.secrets\` — never the value |
| \`project\`, \`region\` in provider/vars | \`google.project_id\`, \`google.region\` |
| Cloud Run / GKE endpoint you do **not** run locally | proxy route \`upstream.url\` |
| \`google_sql_*\`, Pub/Sub, buckets | usually just env keys the local service needs |

## Phase 2 — Draft the configuration

Write modular files when there is more than one service — it keeps diffs small
and matches how the demo platform is laid out:

\`\`\`
.devctl/
  config.yaml          # version, project, google, templates, profiles, proxy, logs
  services/<name>.yaml # one file per service; the FILENAME is the service key
  profiles/<name>.yaml
\`\`\`

Always start \`config.yaml\` with the schema hint so the user's editor completes
field names:

\`\`\`yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/amr-m-abdelgawad/devctl/main/schema/devctl.config.schema.json
version: 1
\`\`\`

Read \`references/authoring.md\` before writing YAML. It carries the rules the
JSON Schema does not state — the ones the loader enforces and rejects on.

Guidance that shapes a good first config:

- **Templates over repetition.** Two services sharing a language or runner
  should \`extends\` a template that holds \`health\` cadence, \`logs\`, \`restart\`.
- **Dependencies are start-order, not networking.** Declare \`dependencies\` only
  where one service genuinely cannot start usefully before another.
- **Cross-service URLs use references**, not hard-coded ports:
  \`API_URL: http://127.0.0.1:\${services.invoices-api.ports.http}\`. This keeps
  working when a port changes or is \`auto\`.
- **Profiles are how people actually start things.** Give at least a small one
  (the API and its dependency) and a full one. \`devctl start\` with no arguments
  uses the active profile, then the first configured profile — so make the
  first-alphabetically profile a sensible default.
- **Health checks that mean something.** An HTTP service with a \`/health\`
  endpoint should use \`type: http\`; a plain \`process\` check only proves the pid
  is alive and will not catch a wedged service.
- **Proxy routes only when the repo needs injected auth** (IAP, service-account
  impersonation) or must reach a remote upstream. A repo with no cloud auth
  does not need \`proxy.enabled: true\`.

## Secrets: name-only, always

devctl already reads dotenv files itself. The correct wiring is to declare the
source and name the keys — never to copy values:

\`\`\`yaml
environment:
  sources: [dotenv]          # repo root then working_dir: .env, .env.development, .env.local, .env.<profile>
  secrets:
    DB_PASSWORD: projects/my-project/secrets/db-password   # a resource NAME
\`\`\`

\`\`\`yaml
# in a service
environment:
  required: [DATABASE_URL, AUTH_URL]   # start fails if still empty after the merge
  defaults:
    LOG_LEVEL: INFO
\`\`\`

### \`.env.example\` is not a \`.env\`

The dotenv source reads \`.env\`, \`.env.development\`, \`.env.local\` and
\`.env.<profile>\`. It does **not** read \`.env.example\` or \`.env.sample\`. Those
are the best place to learn which keys exist — and reading them in full is
safe, since they hold placeholders — but a key that only exists there is
unset at start.

So when the repo ships an example file and no real one, do **not** simply
copy its keys into \`environment.required\` and stop. Pick one:

- List them as \`required\` **and** tell the user, in your final report, that
  they must \`cp .env.example .env\` and fill it in before the first
  \`devctl start\`. This is the better default: it fails fast with a precise
  message naming the missing key.
- Or leave them out of \`required\` for now, and say which keys you deliberately
  left unenforced.

What you must not do is produce a config whose first start fails with
\`missing required environment variable\` and no explanation of why — that reads
as a broken config when it is actually correct and under-documented.

Rules you must hold to:

- Do not copy a value out of \`.env\`, \`.tfvars\`, a keystore, or CI config into
  any YAML you write.
- Do not echo discovered secret values into your own output either — report the
  **key names** you found, not what they contain.
- Add \`secret_manager\` to \`environment.sources\` only when values genuinely look
  like \`projects/*/secrets/*\`; that source throws if it is listed and the fetch
  fails.
- If a \`.env\` file is committed and contains real credentials, say so — that is
  a finding worth reporting, separate from the config work.

## Phase 3 — Validate

This is not optional, and it is a loop: fix, re-run, repeat until clean.

\`\`\`bash
devctl config validate
\`\`\`

\`\`\`bash
devctl config show
\`\`\`

\`validate\` checks YAML syntax, required fields, unknown fields, service and
profile references, dependency cycles, duplicate ports, identities, proxy
routes (including per-service \`proxy\` fragments merged at load), and
environment references. Every message names the exact path
(\`services.api.health.url is required for http health checks\`), so fix the path
it names rather than rewriting the file.

When devctl's MCP server is connected, \`validate_config\` does the same thing
without a shell, and it additionally accepts **candidate text** — so you can
check a draft *before* writing it:

\`\`\`
validate_config { "text": "<the config.yaml you are about to write>" }
\`\`\`

Either way, do not substitute \`reload_config\` for validation: reload runs
against a daemon and rejects the whole change, which is a slower and less
specific way to learn the same thing.

## Phase 4 — Verify it actually runs

A config that validates can still be wrong: a bad command, a health URL that
never answers, a dependency in the wrong direction.

\`\`\`bash
devctl start --profile <smallest-profile>
\`\`\`

\`\`\`bash
devctl status
\`\`\`

\`\`\`bash
devctl doctor
\`\`\`

Then read the logs of anything that is not \`HEALTHY\`:

\`\`\`bash
devctl logs <service> --level ERROR
\`\`\`

Stop when you are done, and take the daemon down if you started it:

\`\`\`bash
devctl down
\`\`\`

**After any failed start, run \`devctl down\` before retrying.** A service that
got far enough to bind its port and then failed its health check can still be
holding that port, so the retry fails for a completely different reason than
the first attempt did — and reads like a config error when the config is fine.
Clearing the daemon first keeps you debugging one problem at a time.

Two failures worth recognising, because they look alike and are not:

- \`service X missing required environment variable K\` — \`environment.required\`
  did its job. The key is genuinely unset: usually the repo ships \`.env.example\`
  but no \`.env\`, since \`.env.example\` is not one of the files the dotenv source
  reads. Tell the user to create it; do not "fix" it by deleting the
  requirement or inventing a value.
- \`service X did not become healthy in time\` — the process started but the
  probe never passed. Check the health URL and port against what the command
  actually binds, and raise \`startup.timeout_seconds\` for slow dev servers
  before assuming the command is wrong.

### When the devctl MCP server is connected

If the agent has devctl's MCP server attached, prefer its tools for the
read-and-observe half of this phase — they return structured data and do not
need a shell:

| Instead of | Use |
|---|---|
| \`devctl status\` | \`list_services\`, \`get_status\` |
| \`devctl logs …\` | \`get_logs\` (200/page; page with \`cursor\` from \`next_cursor\`) |
| \`devctl doctor\` | \`run_doctor\` |
| \`devctl config show\` | \`get_config\` |
| \`devctl start --profile p\` | \`start_services\` with \`profile: p\` |
| \`devctl reload\` | \`reload_config\` |
| \`devctl config validate\` | \`validate_config\` (also takes candidate \`text\`) |

\`devctl down\` has no MCP equivalent — use the CLI. MCP tools need the bearer token
from \`devctl mcp\`; if calls fail with 401, the token is stale — re-copy the
snippet rather than retrying.

## Reporting

Finish with:

1. What you found — services, their ports, what you inferred from Terraform.
2. What you wrote — the file list.
3. \`devctl config validate\` output (clean, or what remains).
4. What you could **not** determine and left as a placeholder — service-account
   emails, IAP audiences, and remote upstream URLs are the usual ones. Name
   them explicitly; a plausible-looking wrong SA email is worse than a marked
   gap.

## References

- \`references/discovery.md\` — signal → service mapping per ecosystem, including
  Terraform, docker-compose, and Kubernetes.
- \`references/authoring.md\` — the loader's real rules: allowed fields, port and
  reference constraints, health/identity/proxy requirements, common rejections.

Both are also served by the MCP server itself, as
\`get_setup_guide { "section": "discovery" | "authoring" }\` — the same text,
compiled into the devctl binary. If you reached this procedure through MCP,
there is nothing to install: fetch the sections you need from there.

### Starting from nothing

\`devctl mcp --on\` works in a repository with no \`.devctl\` at all — the daemon
boots in **setup mode**, which is what makes "install devctl, turn on MCP, ask
the agent to set it up" a complete path. In that state \`get_status\` reports
\`setup_mode: true\`, no service can start, and \`validate_config\` with no
arguments reports the missing configuration rather than a parse error. Draft,
validate the candidate text, write the files, then call \`reload_config\`: setup
mode clears on the reload that finds a valid configuration.
`,
  authoring: `# Authoring rules the loader enforces

The JSON Schema (\`schema/devctl.config.schema.json\`) describes the shape.
This file describes what the **loader and validator actually reject** — the
rules that turn a schema-plausible config into one that fails at
\`devctl config validate\`. Check anything you are unsure of here before writing.

---

## Unknown fields are rejected everywhere

Not warned about — rejected, with the offending path named. These are the
complete allowlists.

**Top level:** \`version\` \`project\` \`google\` \`profiles\` \`templates\` \`services\`
\`proxy\` \`logs\` \`auth\` \`shutdown\` \`ui\` \`secrets\` \`doctor\` \`plugins\`
\`environment\`

**Service** (and \`templates.<name>\`, same shape): \`extends\` \`description\`
\`command\` \`shell\` \`working_dir\` \`dependencies\` \`ports\` \`environment\` \`health\`
\`identity\` \`logs\` \`restart\` \`startup\` \`capabilities\` \`proxy\`

| Section | Allowed keys |
|---|---|
| \`project\` | \`name\` |
| \`google\` | \`project_id\` \`region\` |
| \`profiles.<name>\` | \`services\` \`environment\` |
| \`service.health\` | \`type\` \`url\` \`address\` \`command\` \`interval_seconds\` \`timeout_seconds\` |
| \`service.identity\` | \`type\` \`mode\` \`service_account\` |
| \`service.restart\` | \`enabled\` \`policy\` \`max_retries\` \`backoff_seconds\` |
| \`service.startup\` | \`wait_for_healthy\` \`timeout_seconds\` |
| \`service.logs\` | \`stdout\` \`stderr\` |
| \`service.environment\` | \`required\` \`defaults\` + arbitrary \`KEY: value\` pairs |
| \`proxy\` | \`enabled\` \`listen\` \`token_endpoint\` \`routes\` |
| \`proxy.listen\` | \`host\` \`port\` |
| \`proxy.token_endpoint\` | \`enabled\` \`host\` \`port\` |
| \`route\` | \`name\` \`match\` \`upstream\` \`auth\` |
| \`route.match\` | \`host\` \`path\` |
| \`route.upstream\` | \`url\` |
| \`route.auth\` | \`type\` \`identity\` \`audience\` \`service_account\` |
| \`logs\` | \`max_memory_events\` \`persistence\` |
| \`logs.persistence\` | \`enabled\` \`directory\` \`retention_days\` \`max_session_logs\` |
| \`auth\` | \`refresh_threshold_seconds\` |
| \`shutdown\` | \`stop_services_on_exit\` \`grace_seconds\` |
| \`ui\` | \`theme\` \`keymap\` |
| \`secrets\` | \`extra_markers\` \`extra_patterns\` |
| \`doctor\` | \`tools\` (each \`{ name, command }\`) |
| \`plugins[]\` | \`path\` |
| \`environment\` | \`sources\` \`secrets\` |

There is no \`depends_on\`, no \`image\`, no \`build\`, no \`volumes\`, no \`replicas\`,
no \`env_file\` — those are compose/k8s spellings and will be rejected. Translate
them.

---

## Required, at minimum

- \`version: 1\`. Anything else: *unsupported config version N; no migration is
  available.*
- **At least one service.** An empty or missing \`services\` map fails with *at
  least one service must be defined* — so a proxy-only or profiles-only config
  is not valid.
- Every service needs a non-empty \`command\`.

---

## Ports

- **Globally unique across all services.** Two services on \`8000\` gives
  *duplicate port 8000 used by api and worker*. This is the single most common
  failure when onboarding a repo whose services each assumed they owned the
  default port.
- Range 1–65535.
- Forms accepted: a named map (\`ports: { http: 8000 }\`, preferred), a list, a
  bare number, or \`auto\`. \`auto\` is exempt from the uniqueness check —
  devctl allocates at start.
- Name the port \`http\` when it serves HTTP.
- Prefer the explicit \`\${services.X.ports.http}\` reference form. The short
  \`\${services.X.port}\` form is only unambiguous for a single-port service: once
  the service is running it prefers the assigned port named \`http\`, but when it
  resolves against the configuration it takes the **first port declared**,
  whatever its name. Two forms of the same reference disagreeing on a
  multi-port service is a genuinely confusing bug to chase.

## References

\`\${services.<name>.ports.<portname>}\` and \`\${services.<name>.port}\` are the
supported forms. Anything else — \`\${env.FOO}\`, \`\${project.name}\` — throws.

- The referenced service must exist and the named port must be defined, or
  validation fails with *unresolvable reference*.
- References resolve inside service \`environment\` values, \`defaults\`, profile
  environments and dotenv values, before the process starts.
- Use them for every cross-service URL. Hard-coded ports silently break when a
  port changes or is switched to \`auto\`.

## Dependencies

- Must name a service that exists.
- A service may not depend on itself.
- Cycles are rejected: *dependency cycle: a → b → a*.
- Direction: \`dependencies\` means "start these first". \`start x\` walks **up**
  and starts x's dependencies; \`stop x\` walks **down** and stops x's
  *dependents*, never its dependencies.

## Commands and \`shell\`

A command whose argv contains any of \`|\` \`||\` \`&&\` \`;\` \`>\` \`>>\` \`<\` \`&\` is
rejected unless \`shell: true\`:

\`\`\`yaml
# rejected
command: "npm run build && npm start"

# correct
command: "npm run build && npm start"
shell: true

# better — no shell needed
command: [npm, start]
\`\`\`

Prefer argv lists. A string command is split on whitespace, which mangles
arguments containing spaces.

## \`working_dir\`

Relative to the **repository root** — the directory containing \`.devctl\` — not
the process cwd, and not the \`.devctl\` directory itself.

---

## Health

| \`type\` | Also requires |
|---|---|
| \`http\` | \`url\` — omit it and you get *health.url is required for http health checks* |
| \`tcp\` | \`address\`, **or** at least one port defined on the service |
| \`command\` | \`health.command\` (non-empty) |
| \`process\` or omitted | nothing; only checks the pid is alive |

Any other \`type\` is rejected — *health.type must be http, tcp, process, or
command* — **unless** \`plugins\` is non-empty. That exemption is not approval:
plugins load after validation, so the supervisor re-checks the type at boot and
at reload. A custom type no plugin provides fails as a *reload rejection*, not
a config error, which is much harder to diagnose. Only use a custom type when
you can point at the plugin that registers it.

Defaults when omitted: interval 2s, timeout 2s.

## Identity

- \`type: user\` (or omitted) needs nothing else.
- \`type: service_account\` (or \`service\`) **requires** \`service_account\`, and it
  must contain \`@\` — *service_account must be an email*.
- \`mode\` is an accepted alias of \`type\`.
- Any other type behaves like a custom health type: allowed only with
  \`plugins\` set, re-checked at boot.

Never fabricate an SA email. If Terraform interpolates it beyond what you can
resolve, leave a clearly-marked placeholder and tell the user.

## Restart

\`policy\` must be \`never\`, \`on_failure\`, or \`always\`. \`enabled: true\` with no
policy behaves as \`on_failure\`.

\`max_retries\` is a real budget: it resets on a manual stop/start/restart and
after a sustained healthy run, but an automatic health-triggered restart
preserves it across its own cycle.

## Capabilities

Documentation for doctor, not behaviour. Only these are accepted:
\`google\` \`google_api\` \`iap\` \`network\` \`service_identity\` \`local_http\`.
Anything else is rejected.

---

## Proxy

- \`proxy.listen.port\` is **required** when \`proxy.enabled: true\`.
- \`proxy.listen.host\` must be an IP or \`localhost\`. \`0.0.0.0\` is rejected.
- \`proxy.token_endpoint.host\` must be loopback; \`0.0.0.0\` is rejected.
- Every route needs a \`name\` and an \`upstream.url\`.
- **Route names must be unique** — including names generated from per-service
  \`proxy\` fragments.
- \`auth.type: iap\` requires **both** \`audience\` and \`auth.identity.type\`. A
  missing identity type on an IAP route is a configuration error, not a
  default.
- An identity of \`service\` / \`service_account\` requires an SA email, from
  either \`auth.identity.service_account\` or the route's \`auth.service_account\`.
- \`auth.type: none\` means no auth at all — any identity left on such a route is
  ignored entirely, and will not be probed at start or by doctor.

### Per-service route fragments

A service's \`proxy\` key is one route or a list. At load they append into the
**same** global \`proxy.routes\` list, named \`<service>\` or \`<service>-<n>\`:

\`\`\`yaml
services:
  api:
    command: [python3, main.py]
    proxy:
      - match: { path: /api }
        upstream: { url: "http://127.0.0.1:8000" }
\`\`\`

That generates a route named \`api\`. So a service named \`api\` **and** a global
route named \`api\` collide — *duplicate route name api*. Watch for this when
mixing both styles.

Matching is host + optional path prefix. There is no path rewriting or
stripping: the matched path is forwarded to the upstream as-is.

---

## Modular layout

When the main file is \`.devctl/config.yaml\`, these merge in automatically:

\`\`\`
.devctl/services/<name>.yaml   → services.<name>          (FILENAME is the key)
.devctl/profiles/<name>.yaml   → profiles.<name>
.devctl/proxy/routes.yaml      → proxy.routes             (see the wrapper below)
\`\`\`

A service or profile file contains that object's body **only** — no \`services:\`
wrapper, no \`version:\`. Getting this wrong reads oddly: a \`services:\` wrapper
inside \`.devctl/services/api.yaml\` reports
\`unknown fields: services.api.services\`.

\`proxy/routes.yaml\` is the exception: it accepts either a full \`proxy:\` wrapper
or a bare top-level \`routes:\` list. Both append to the same global route list.

\`\`\`yaml
# .devctl/proxy/routes.yaml — wrapper form, also lets you set proxy.listen here
proxy:
  routes:
    - name: invoices-api
      match: { host: invoices-api.local }
      upstream: { url: "http://127.0.0.1:18000" }
\`\`\`

\`\`\`yaml
# .devctl/proxy/routes.yaml — bare form, equivalent for routes alone
routes:
  - name: invoices-api
    match: { host: invoices-api.local }
    upstream: { url: "http://127.0.0.1:18000" }
\`\`\`

Pick one. Both keys in the same file append **both** lists, which trips the
duplicate-route-name check.

Overlays merge after the repo config, later wins:
built-in defaults → repo \`.devctl\` → \`~/.devctl/config.local.yaml\` →
\`.devctl/config.local.yaml\` — the repo-local overlay wins over the home one.
Overlays are presence-aware:
\`false\`, \`0\` and
empty collections in an overlay do override, so \`proxy.enabled: false\` in a
local overlay genuinely turns the proxy off.

---

## Environment

Merge order — later sources win:

\`\`\`
process → profile → dotenv → generated → keychain → secret_manager → defaults → vars → runtime
\`\`\`

\`process\`, \`defaults\`, \`vars\` and \`runtime\` always run. Listing
\`environment.sources\` **adds** optional sources (\`profile\`, \`dotenv\`,
\`generated\`, \`keychain\`, \`secret_manager\`) to that always-on set — it does not
replace it, and it does not reorder anything.

- \`dotenv\` reads repo root then \`working_dir\`: \`.env\`, \`.env.development\`,
  \`.env.local\`, \`.env.<profile>\`.
- \`keychain\` and \`secret_manager\` throw when listed and the fetch fails, so
  only list them when the repo genuinely uses them.
- \`environment.required\` on a service fails the start if those keys are still
  empty after the whole merge — the right place to encode "this cannot run
  without X".

Runtime values devctl injects: \`SERVICE_PORT\`, \`SERVICE_HOST\`,
\`DEVCTL_PROXY_URL\`, \`DEVCTL_SERVICE_NAME\`, \`DEVCTL_ENVIRONMENT\`,
\`DEVCTL_TOKEN_URL\`, \`DEVCTL_INTERNAL_TOKEN\`. Do not define these yourself.

---

## Templates

\`\`\`yaml
templates:
  python-http:
    health: { type: http, interval_seconds: 2, timeout_seconds: 1 }
    logs: { stdout: true, stderr: true }
    restart: { policy: on_failure, max_retries: 2, backoff_seconds: 1 }

services:
  api:
    extends: python-http
    command: [python3, main.py]
    health: { url: "http://127.0.0.1:8000/health" }   # merged field-by-field
\`\`\`

- \`extends\` must name a template that exists.
- Nested sections merge **field by field**, so a service can override one
  health field without restating the rest.
- A template is not a service and is never started.

---

## Reading validation output

Every message names its path. Fix the path it names.

| Message | Meaning |
|---|---|
| \`at least one service must be defined\` | empty/missing \`services\` |
| \`duplicate port N used by X and Y\` | two services pinned the same port |
| \`services.X.command is required\` | missing or empty command |
| \`services.X.command contains shell metacharacters\` | add \`shell: true\` or use argv |
| \`services.X.dependencies: unknown service "Y"\` | typo, or Y lives in a file you did not create |
| \`dependency cycle: a → b → a\` | remove an edge |
| \`services.X.health.url is required for http health checks\` | add \`url\`, or change the type |
| \`services.X.identity.service_account must be an email\` | placeholder left unresolved |
| \`services.X.environment.K: unresolvable reference \${…}\` | referenced service or port name does not exist |
| \`services.X.capabilities: unknown capability "c"\` | only the six listed above are accepted |
| \`profiles.P references unknown service "S"\` | profile lists a service that is not defined |
| \`proxy.routes[i]: duplicate route name N\` | often a per-service fragment colliding with a global route |
| \`proxy.routes[i].auth.audience is required when auth.type is iap\` | IAP needs both audience and identity.type |
| \`proxy.listen.port is required when proxy.enabled is true\` | pin a port |
| \`unsupported config version N (expected 1)\` | \`version:\` must be \`1\` |
| \`unknown fields: services.a.depends_on\` | not in the allowlists at the top of this file — usually a compose or k8s spelling |

Every message above is the validator's exact wording. \`devctl config validate\`
prints one per line and exits 2; a clean run prints \`configuration is valid\`
and exits 0.
`,
  discovery: `# Discovery: repository signal → devctl service

How to turn what a repository contains into the service list you draft from.
Read the signals in roughly this order — the earlier ones describe *how the
repo is actually run*, the later ones describe *where it is deployed*.

Throughout: a signal produces a **devctl service** only when the repo contains
runnable source and a start command for it. Everything else is either an
environment key, a proxy upstream, or context.

---

## 1. Task runners and process managers (highest signal)

These already encode "the commands a developer runs", which is exactly what a
devctl service is.

### docker-compose

\`docker-compose.yml\` / \`compose.yaml\` is the single best source. Map it, do not
copy it:

| Compose | devctl |
|---|---|
| \`services.<name>\` | \`services.<name>\` (same key) |
| \`command\` / image entrypoint | \`command\` — but see below |
| \`ports: ["8000:8000"]\` | \`ports: { http: 8000 }\` (the **host** side) |
| \`depends_on\` | \`dependencies\` |
| \`environment\` | \`environment\` vars / \`defaults\` |
| \`env_file\` | \`environment.sources: [dotenv]\` at the top level |
| \`healthcheck.test\` | \`health: { type: command, command: [...] }\`, or better, an \`http\` check if the container exposes one |
| \`working_dir\` / \`build.context\` | \`working_dir\` (relative to repo root) |

The trap: compose runs **containers**, devctl runs **host processes**. A
compose service whose only definition is \`image: postgres:16\` has no local
source and no host command — it is not a devctl service. Either leave it out
and note that the developer starts it separately, or keep it as an explicit
container command (\`docker run …\`) if the team genuinely wants devctl to own
it. Say which you chose.

### Procfile

Nearly a direct translation — one line, one service:

\`\`\`
web: bundle exec puma -p 3000    →  services.web.command, ports.http: 3000
worker: bundle exec sidekiq      →  services.worker.command
\`\`\`

### Makefile / Taskfile / justfile

Look for targets named \`dev\`, \`run\`, \`serve\`, \`start\`, \`watch\`. These usually
contain the real command. Beware targets that are pipelines — a command
containing \`|\`, \`&&\`, \`;\`, \`>\` or \`&\` needs \`shell: true\` in devctl.

### Foreman / overmind / honcho / air / nodemon configs

Same shape as Procfile; read them for the command and the port.

---

## 2. Per-language project files

Scan to depth 3, excluding \`node_modules\`, \`.venv\`, \`vendor\`, \`target\`, \`dist\`.
Each hit is a candidate service; its directory becomes \`working_dir\`.

### Node / Bun / Deno — \`package.json\`

- \`scripts.dev\` → the command. Prefer the repo's own package manager: \`bun run
  dev\`, \`npm run dev\`, \`pnpm dev\`. Check for a lockfile to pick correctly
  (\`bun.lock\` → bun, \`pnpm-lock.yaml\` → pnpm, \`yarn.lock\` → yarn).
- Port: look in \`vite.config.*\` (\`server.port\`), \`next.config.*\`, an explicit
  \`--port\` flag, or \`PORT\` in \`.env\`.
- Vite/Next dev servers can be slow to first respond — give them
  \`startup.timeout_seconds: 45\` rather than the default.

### Python — \`pyproject.toml\`, \`requirements.txt\`, \`manage.py\`

- FastAPI/Starlette: \`uvicorn app.main:app --port 8000 --reload\`
- Django: \`python manage.py runserver 0.0.0.0:8000\` (rewrite the bind to
  \`127.0.0.1\` for local use)
- Flask: \`flask --app app run --port 5000\`
- A bare \`main.py\` with \`if __name__ == "__main__"\` → \`python3 main.py\`
- Celery workers: \`celery -A app worker\` — no port, use \`type: process\` health.

### Go — \`go.mod\`

\`go run ./cmd/<name>\` or \`air\` when \`.air.toml\` is present. Port usually in a
\`flag.String("addr", ":8080", …)\` or read from env.

### Rust — \`Cargo.toml\`

\`cargo run --bin <name>\`, or \`cargo watch -x run\` when the dev tooling has it.

### JVM — \`pom.xml\`, \`build.gradle\`

\`./mvnw spring-boot:run\`, \`./gradlew bootRun\`. Port from
\`application.properties\` / \`application.yml\` (\`server.port\`).

### Ruby — \`Gemfile\`

\`bin/rails server -p 3000\`, or read the Procfile.

---

## 3. Environment files

Collect **key names**, never values.

\`\`\`bash
# names only
grep -hoE '^[A-Za-z_][A-Za-z0-9_]*=' .env .env.* */.env 2>/dev/null | tr -d '=' | sort -u
\`\`\`

devctl's \`dotenv\` source already reads, in order: repo root then the service's
\`working_dir\`, each as \`.env\`, \`.env.development\`, \`.env.local\`,
\`.env.<profile>\` — later wins. So:

- Add \`environment.sources: [dotenv]\` once, at the top level.
- Do **not** re-declare dotenv keys as service \`environment\` vars; that
  duplicates the value into YAML for no benefit.
- Do list keys the service genuinely cannot start without under
  \`environment.required\` — that turns a confusing runtime crash into a clear
  startup error.
- \`.env.example\` / \`.env.sample\` is the best source for *which* keys exist, and
  is safe to read in full — it holds placeholders. But devctl does **not** read
  it: the dotenv source only loads \`.env\`, \`.env.development\`, \`.env.local\` and
  \`.env.<profile>\`. A key that exists only in the example file is unset at
  start, so if you mark it \`required\`, say in your report that the user must
  create the real \`.env\` first. See the SKILL's secrets section.

Cross-service URLs found in \`.env\` (\`API_URL=http://localhost:8000\`) should be
rewritten as references in the config so they survive a port change:
\`API_URL: http://127.0.0.1:\${services.api.ports.http}\`.

---

## 4. Kubernetes / Helm / Skaffold

Deployment descriptors, like Terraform — infer, do not transcribe.

- \`Deployment.spec.containers[].ports.containerPort\` → a sensible local port
- \`env\` / \`envFrom.configMapRef\` → env key names
- \`envFrom.secretRef\` → secret names, values never
- \`livenessProbe.httpGet.path\` → your \`health.url\` path
- \`skaffold.yaml\` \`build.artifacts[].context\` → candidate \`working_dir\`s, and
  its \`deploy\` section tells you what actually runs together

A Deployment for an image the repo does not build is not a local service.

---

## 5. Terraform

The direction matters: Terraform describes deployed infrastructure; devctl runs
local processes. **A Terraform resource is never a devctl service on its own.**

### What to extract

\`\`\`bash
grep -rhoE 'resource "google_[a-z_]+"' --include='*.tf' . | sort -u
\`\`\`

| Resource | Contributes |
|---|---|
| \`provider "google"\` / \`var.project_id\` / \`var.region\` | \`google.project_id\`, \`google.region\` |
| \`google_service_account\` | candidate \`identity.service_account\` (a service that impersonates it locally) or a route's \`auth.identity.service_account\` |
| \`google_iap_*\`, \`google_iap_client\`, IAP brand | route \`auth.type: iap\`; the OAuth client ID or resource name is the \`audience\` |
| \`google_secret_manager_secret\` | a key under \`environment.secrets\`, mapped to \`projects/<p>/secrets/<name>\`; add \`secret_manager\` to \`environment.sources\` |
| \`google_cloud_run_v2_service\`, \`google_compute_backend_service\` | if the repo builds it → the local service it corresponds to; if not → a proxy route \`upstream.url\` |
| \`google_sql_database_instance\`, Pub/Sub topics, GCS buckets | env keys the local service needs; no devctl object of their own |
| \`google_project_iam_member\` on a SA | tells you which SA a service is *meant* to run as — good evidence for \`identity\` |

### The judgement call

For each Cloud Run / GKE workload in Terraform, ask: **does this repo contain
the source and a way to start it?**

- Yes → it is a devctl service. Terraform tells you its identity and which
  secrets it reads.
- No → it is a dependency your local services call. If it needs injected auth
  (IAP, impersonation), give it a **proxy route** so local callers hit
  \`127.0.0.1:<proxy>\` and devctl attaches the credential. If it needs no auth,
  it is just a URL in the environment.

### Placeholders, not guesses

Service-account emails and IAP audiences are exact strings that fail obscurely
when wrong. If Terraform uses interpolation you cannot resolve
(\`"\${var.prefix}-api@\${var.project}.iam.gserviceaccount.com"\`), write the
literal shape you *can* determine and flag it for the user, rather than
resolving the variables yourself and shipping a plausible fabrication.

---

## 6. CI configuration

\`.github/workflows/*.yml\`, \`.gitlab-ci.yml\`, \`Jenkinsfile\` are a useful
cross-check: the \`services:\` block of a CI job usually lists the backing
services (Postgres, Redis) a developer also needs, and the test setup steps
often reveal the true start command and the env keys required.

---

## Assembling the draft

After the sweep, you should be able to fill this table for every candidate:

| name | working_dir | command | port | dependencies | health | required env |
|---|---|---|---|---|---|---|

Rules for turning that into YAML:

- **Ports must be globally unique.** When the repo does not pin them, assign a
  contiguous private band (\`18000+\`) or use \`auto\`.
- **Dependency edges must be acyclic**, and should reflect "cannot start
  usefully without", not "talks to".
- **Group repeated shape into a template** — same language and runner usually
  means the same \`health\` cadence, \`logs\` and \`restart\` policy.
- **Profiles**: at minimum a small one (one service plus its dependencies) and
  a full one. Remember that a bare \`devctl start\` falls back to the first
  configured profile, and the TUI's default is the first profile
  alphabetically — so name them with that in mind.
`,
} as const;

export type GuideSection = keyof typeof GUIDE_SECTIONS;
